
# MQTT Acquire Config
com.hp.pushserver.mqtt.acquire:
    #MQTT服务监听端口
    serverAddress: 127.0.0.1:1884
    userName: jackl
    password: 123456
    clientId: pushserver
    #消费的topic 多个以半角逗号分隔
    subscribeTopic: #
    publicTopicPrefix: /d/

#MQ服务器相关信息
com.hp.pushserver.mq:
    exchangeName: exchange
    host: 127.0.0.1
    port: 5672
    userName: jackl
    password: 123456
    #消费的queue是否是持久化，为true，消费者离线时消息将会积压在MQ中，如果修改了此值启动出现错误，需要在rabbitmq中将相应queue删除然后重启
    durable: true
    #序列化模式 1:str.getBytes ; 2:serialize(str)
    serializeMode: 2
    #消费的routKeys 多个以半角逗号分隔
    consumeRouteKeys: #

# Spring settings
spring:
    profiles.active: dev
